from PyQt5 import QtCore, QtWidgets
from PyQt5 import QtGui

from personality.characters import *
from person import Person

ENFJ()

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1200, 900)
        MainWindow.setWindowIcon(QtGui.QIcon('C:/div/Projects/Python/math_project/app/icon.png'))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayoutWidget = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(20, 20, 551, 661))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_9 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_9.setObjectName("label_9")
        self.verticalLayout.addWidget(self.label_9)
        self.comboBox_9 = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox_9.setObjectName("comboBox_9")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.comboBox_9.addItem("")
        self.verticalLayout.addWidget(self.comboBox_9)
        self.label_8 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_8.setObjectName("label_8")
        self.verticalLayout.addWidget(self.label_8)
        self.doubleSpinBox_12 = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.doubleSpinBox_12.setObjectName("doubleSpinBox_12")
        self.verticalLayout.addWidget(self.doubleSpinBox_12)
        self.label_7 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_7.setObjectName("label_7")
        self.verticalLayout.addWidget(self.label_7)
        self.doubleSpinBox_13 = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.doubleSpinBox_13.setObjectName("doubleSpinBox_13")
        self.verticalLayout.addWidget(self.doubleSpinBox_13)
        self.label_6 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_6.setObjectName("label_6")
        self.verticalLayout.addWidget(self.label_6)
        self.doubleSpinBox_14 = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.doubleSpinBox_14.setObjectName("doubleSpinBox_14")
        self.verticalLayout.addWidget(self.doubleSpinBox_14)
        self.label_5 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_5.setObjectName("label_5")
        self.verticalLayout.addWidget(self.label_5)
        self.doubleSpinBox_15 = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget)
        self.doubleSpinBox_15.setObjectName("doubleSpinBox_15")
        self.verticalLayout.addWidget(self.doubleSpinBox_15)
        self.label_4 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.comboBox_4 = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox_4.setObjectName("comboBox_4")
        self.comboBox_4.addItem("")
        self.comboBox_4.addItem("")
        self.verticalLayout.addWidget(self.comboBox_4)
        self.label_3 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.comboBox_3 = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox_3.setObjectName("comboBox_3")
        self.comboBox_3.addItem("")
        self.comboBox_3.setItemText(0, "")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.comboBox_3.addItem("")
        self.verticalLayout.addWidget(self.comboBox_3)
        self.label_2 = QtWidgets.QLabel(self.verticalLayoutWidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.comboBox_2 = QtWidgets.QComboBox(self.verticalLayoutWidget)
        self.comboBox_2.setObjectName("comboBox_2")
        self.comboBox_2.addItem("")
        self.comboBox_2.addItem("")
        self.verticalLayout.addWidget(self.comboBox_2)
        self.verticalLayoutWidget_2 = QtWidgets.QWidget(self.centralwidget)
        self.verticalLayoutWidget_2.setGeometry(QtCore.QRect(600, 80, 571, 601))
        self.verticalLayoutWidget_2.setObjectName("verticalLayoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.verticalLayoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_10 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_10.setObjectName("label_10")
        self.verticalLayout_2.addWidget(self.label_10)
        self.doubleSpinBox = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget_2)
        self.doubleSpinBox.setObjectName("doubleSpinBox")
        self.verticalLayout_2.addWidget(self.doubleSpinBox)
        self.label_11 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_11.setObjectName("label_11")
        self.verticalLayout_2.addWidget(self.label_11)
        self.doubleSpinBox_2 = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget_2)
        self.doubleSpinBox_2.setObjectName("doubleSpinBox_2")
        self.verticalLayout_2.addWidget(self.doubleSpinBox_2)
        self.label_12 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_12.setObjectName("label_12")
        self.verticalLayout_2.addWidget(self.label_12)
        self.doubleSpinBox_3 = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget_2)
        self.doubleSpinBox_3.setObjectName("doubleSpinBox_3")
        self.verticalLayout_2.addWidget(self.doubleSpinBox_3)
        self.label_13 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_13.setObjectName("label_13")
        self.verticalLayout_2.addWidget(self.label_13)
        self.doubleSpinBox_4 = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget_2)
        self.doubleSpinBox_4.setObjectName("doubleSpinBox_4")
        self.verticalLayout_2.addWidget(self.doubleSpinBox_4)
        self.label_18 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_18.setObjectName("label_18")
        self.verticalLayout_2.addWidget(self.label_18)
        self.doubleSpinBox_9 = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget_2)
        self.doubleSpinBox_9.setObjectName("doubleSpinBox_9")
        self.verticalLayout_2.addWidget(self.doubleSpinBox_9)
        self.label_19 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_19.setObjectName("label_19")
        self.verticalLayout_2.addWidget(self.label_19)
        self.doubleSpinBox_10 = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget_2)
        self.doubleSpinBox_10.setObjectName("doubleSpinBox_10")
        self.verticalLayout_2.addWidget(self.doubleSpinBox_10)
        self.label_20 = QtWidgets.QLabel(self.verticalLayoutWidget_2)
        self.label_20.setObjectName("label_20")
        self.verticalLayout_2.addWidget(self.label_20)
        self.doubleSpinBox_11 = QtWidgets.QDoubleSpinBox(self.verticalLayoutWidget_2)
        self.doubleSpinBox_11.setObjectName("doubleSpinBox_11")
        self.verticalLayout_2.addWidget(self.doubleSpinBox_11)
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(600, 10, 561, 51))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(150, 750, 311, 41))
        self.pushButton.setObjectName("pushButton")
        self.label_21 = QtWidgets.QLabel(self.centralwidget)
        self.label_21.setGeometry(QtCore.QRect(610, 690, 561, 171))
        self.label_21.setText("")
        self.label_21.setObjectName("label_21")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1200, 18))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Project"))
        self.label_9.setText(_translate("MainWindow", "Тип характера"))
        self.comboBox_9.setItemText(0, _translate("MainWindow", "ENTP"))
        self.comboBox_9.setItemText(1, _translate("MainWindow", "ENFP"))
        self.comboBox_9.setItemText(2, _translate("MainWindow", "INTP"))
        self.comboBox_9.setItemText(3, _translate("MainWindow", "INFP"))
        self.comboBox_9.setItemText(4, _translate("MainWindow", "ESTP"))
        self.comboBox_9.setItemText(5, _translate("MainWindow", "ESFP"))
        self.comboBox_9.setItemText(6, _translate("MainWindow", "ISTP"))
        self.comboBox_9.setItemText(7, _translate("MainWindow", "ISFP"))
        self.comboBox_9.setItemText(8, _translate("MainWindow", "ESFJ"))
        self.comboBox_9.setItemText(9, _translate("MainWindow", "ENFJ"))
        self.comboBox_9.setItemText(10, _translate("MainWindow", "ISFJ"))
        self.comboBox_9.setItemText(11, _translate("MainWindow", "INFJ"))
        self.comboBox_9.setItemText(12, _translate("MainWindow", "ESTJ"))
        self.comboBox_9.setItemText(13, _translate("MainWindow", "ENTJ"))
        self.comboBox_9.setItemText(14, _translate("MainWindow", "INTJ"))
        self.comboBox_9.setItemText(15, _translate("MainWindow", "ISTJ"))
        self.label_8.setText(_translate("MainWindow", "Величина желания"))
        self.label_7.setText(_translate("MainWindow", "Средства у субъекта"))
        self.label_6.setText(_translate("MainWindow", "Средства, необходимые для достижения цели"))
        self.label_5.setText(_translate("MainWindow", "Неожиданность"))
        self.label_4.setText(_translate("MainWindow", "Наличие объектов"))
        self.comboBox_4.setItemText(0, _translate("MainWindow", "Присутствуют"))
        self.comboBox_4.setItemText(1, _translate("MainWindow", "Отсутствуют"))
        self.label_3.setText(_translate("MainWindow", "Отношение к людям (при наличии)"))
        self.comboBox_3.setItemText(1, _translate("MainWindow", "Нейтральное"))
        self.comboBox_3.setItemText(2, _translate("MainWindow", "Положительное"))
        self.comboBox_3.setItemText(3, _translate("MainWindow", "Отрицательное"))
        self.label_2.setText(_translate("MainWindow", "Время целевого события"))
        self.comboBox_2.setItemText(0, _translate("MainWindow", "Прошло"))
        self.comboBox_2.setItemText(1, _translate("MainWindow", "Будет"))
        self.label_10.setText(_translate("MainWindow", "Физиологические потребности"))
        self.label_11.setText(_translate("MainWindow", "Потребность в безопасности"))
        self.label_12.setText(_translate("MainWindow", "Потребность в принадлежности и любви"))
        self.label_13.setText(_translate("MainWindow", "Потребность в уважении"))
        self.label_18.setText(_translate("MainWindow", "Потребности познавательные"))
        self.label_19.setText(_translate("MainWindow", "Эстетические потребности"))
        self.label_20.setText(_translate("MainWindow", "Потребность в самоактуализации"))
        self.label.setText(_translate("MainWindow", "Типы потребностей"))
        self.pushButton.setText(_translate("MainWindow", "СРЕАГИРОВАТЬ"))
        self.pushButton.clicked.connect(self.push)
        self.doubleSpinBox_12.setMaximum(float('inf'))
        self.doubleSpinBox_12.setMinimum(float('-inf'))
        self.doubleSpinBox_14.setMaximum(float('inf'))
        self.doubleSpinBox_14.setMinimum(0.01)
        self.doubleSpinBox_13.setMaximum(float('inf'))
        self.doubleSpinBox_13.setMinimum(0)
        self.doubleSpinBox.setMaximum(1)
        self.doubleSpinBox.setMinimum(0)
        self.doubleSpinBox_2.setMaximum(1)
        self.doubleSpinBox_2.setMinimum(0)
        self.doubleSpinBox_3.setMaximum(1)
        self.doubleSpinBox_3.setMinimum(0)
        self.doubleSpinBox_4.setMaximum(1)
        self.doubleSpinBox_4.setMinimum(0)
        self.doubleSpinBox_9.setMaximum(1)
        self.doubleSpinBox_9.setMinimum(0)
        self.doubleSpinBox_10.setMaximum(1)
        self.doubleSpinBox_10.setMinimum(0)
        self.doubleSpinBox_11.setMaximum(1)
        self.doubleSpinBox_11.setMinimum(0)
        self.doubleSpinBox_15.setMaximum(float('inf'))
        self.doubleSpinBox_15.setMinimum(0)



    def push(self):
        person = Person(eval(self.comboBox_9.currentText())())
        percents = [
                    self.doubleSpinBox.value(),
                    self.doubleSpinBox_2.value(),
                    self.doubleSpinBox_3.value(),
                    self.doubleSpinBox_4.value(),
                    self.doubleSpinBox_9.value(),
                    self.doubleSpinBox_10.value(),
                    self.doubleSpinBox_11.value()
                ]
        if sum(percents) != 1:
            self.label_21.setText("Сумма типов потребностей\nне равна 1")
            return
        elif self.doubleSpinBox_12.value() == 0:
            self.label_21.setText("Величина желания не может быть равна 0")
            return
        emotion = person.emotion_define(
            desire_value=self.doubleSpinBox_12.value(),
            know_probability=self.doubleSpinBox_14.value(),
            own_probability=self.doubleSpinBox_13.value(),
            needs_percent=percents,
            direction=True if self.comboBox_4.currentText() == "Отсутствуют" else False,
            timeline=True if self.comboBox_2.currentText() == "Прошло" else False,
            surprise_coef=self.doubleSpinBox_15.value(),
            relationship={
                "": None,
                "Нейтральное": 0,
                "Положительное": 1,
                "Отрицательное": -1
            }[self.comboBox_3.currentText()]
        )
        self.label_21.setText(str(emotion))